name: SECSS Local - Backend actual
values:
  - key: baseUrl
    value: 'http://localhost:4000'
  - key: testPassword
    value: SECSS-Testing-2026!
  - key: docAdmin
    value: '1021312836'
  - key: docJefe
    value: '80112233'
  - key: docCelador
    value: '79888777'
  - key: docAprendizSemilla
    value: '1055444333'
  - key: docInvitadoSemilla
    value: '52888999'
  - key: tokenAdmin
    value: ''
  - key: tokenJefe
    value: ''
  - key: tokenCelador
    value: ''
  - key: tokenAprendizSemilla
    value: ''
  - key: tokenInvitadoSemilla
    value: ''
  - key: docAprendizNuevo
    value: ''
  - key: tokenAprendizNuevo
    value: ''
  - key: nuevoAprendizId
    value: ''
  - key: docInvitadoNuevo
    value: ''
  - key: tokenInvitadoNuevo
    value: ''
  - key: nuevoInvitadoId
    value: ''
  - key: nuevoVehiculoId
    value: ''
  - key: nuevoVehiculoInvitadoId
    value: ''
  - key: nuevaEntradaId
    value: ''
  - key: nuevoReporteId
    value: ''
  - key: nuevaPqrsId
    value: ''
  - key: fixtureDir
    value: ''
  - key: passwordInvitadoNuevo
    value: ''
